include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    avoid_print: false
    prefer_single_quotes: true
    require_trailing_commas: true
