name: prive
description: A Global Communcation App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # App Configs
  cupertino_icons: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1
  easy_localization: ^3.0.0
  flutter_local_notifications: ^9.1.4
  permission_handler: ^8.3.0

  # State Management
  provider: 5.0.0
  shared_preferences: ^2.0.9

  # Network
  dio: ^4.0.4
  connectivity_plus: ^2.0.3

  # Audio
  just_audio: ^0.9.18
  record: ^3.0.2

  # Widgets
  cached_network_image: ^3.1.0+1
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.4+4
  intl_phone_field: ^2.1.0
  pin_code_fields: ^7.3.0
  adaptive_dialog: ^1.2.0
  bot_toast: ^4.0.1
  flutter_staggered_animations: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  flutter_rating_bar: ^4.0.0
  lottie: ^1.2.1
  smooth_page_indicator: ^1.0.0+2
  page_indicator: ^0.4.1
  auto_size_text: ^3.0.0
  convex_bottom_bar: ^3.0.0
  intl_phone_number_input: ^0.7.0+2
  bs_flutter_selectbox: ^1.3.0
  timer_count_down: ^2.2.0
  syncfusion_flutter_sliders: ^19.3.55
  grouped_list: ^4.1.0
  flutter_chat_bubble: ^2.0.0
  cool_dropdown: ^1.4.1

  # Utils
  supercharged: ^2.1.1
  intl: ^0.17.0
  share_plus: ^3.0.4
  country_calling_code_picker: ^2.0.0
  font_awesome_flutter: ^9.2.0
  timeago: ^3.1.0
  flutter_contacts: ^1.1.1+2

  # Firebase
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  firebase_messaging: ^11.1.0

  # Stream
  stream_chat_flutter_core: ^3.2.0
  stream_chat_flutter: ^3.2.0
  stream_chat_persistence: ^3.0.0
  stream_chat_localizations: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/prive_app_icon.jpg"

flutter_native_splash:
  background_image: "assets/images/splash_image.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/animations/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black.otf
        - asset: assets/fonts/SF-Pro-Display-BlackItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/SF-Pro-Display-BoldItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
        - asset: assets/fonts/SF-Pro-Display-HeavyItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Light.otf
        - asset: assets/fonts/SF-Pro-Display-LightItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SF-Pro-Display-MediumItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
        - asset: assets/fonts/SF-Pro-Display-SemiboldItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
        - asset: assets/fonts/SF-Pro-Display-ThinItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
        - asset: assets/fonts/SF-Pro-Display-UltralightItalic.otf