name: prive
description: A Global Communcation App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # App Configs
  cupertino_icons: ^1.0.5
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.14
  easy_localization: ^3.0.1
  flutter_local_notifications: ^12.0.3
  permission_handler: ^10.2.0
  uuid: ^3.0.7

  # State Management
  provider: ^6.0.4
  shared_preferences: ^2.0.15

  # Network
  dio: ^4.0.6
  connectivity_plus: ^2.3.9

  # Audio
  just_audio: ^0.9.30
  record: ^4.4.3

  # Widgets
  cached_network_image: ^3.2.2
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.6
  intl_phone_field: ^3.1.0
  pin_code_fields: ^7.4.0
  bot_toast: ^4.0.3
  flutter_staggered_animations: ^1.1.1
  flutter_rating_bar: ^4.0.1
  lottie: ^1.4.3
  smooth_page_indicator: ^1.0.0+2
  page_indicator: ^0.4.1
  auto_size_text: ^3.0.0
  convex_bottom_bar: ^3.1.0+1
  intl_phone_number_input: ^0.7.1
  bs_flutter_selectbox: ^1.3.0
  timer_count_down: ^2.2.1
  syncfusion_flutter_sliders: ^20.3.56
  grouped_list: ^5.1.2
  flutter_chat_bubble: ^2.0.0
  cool_dropdown: ^1.4.2
  blur: ^3.1.0
  community_material_icon: ^5.9.55
  country_dial_code: ^1.2.0
  phone_numbers_parser: ^5.0.5
  flutter_sim_country_code: ^0.1.2
  draggable_widget: ^2.0.0
  flip_card: ^0.6.0
  flutter_swipe_action_cell: ^3.0.4
  badges: ^2.0.3
  dashed_circle: ^0.0.2
  story_view: ^0.14.0
  flutter_carousel_slider: ^1.1.0
  google_fonts: ^3.0.1
  map_launcher: ^2.4.0
  carousel_slider: ^4.1.1
  awesome_dialog: ^3.0.2
  flutter_staggered_grid_view: ^0.4.0
  rflutter_alert: ^2.0.4
  modal_bottom_sheet:
    git:
      url: https://github.com/1AhmedYasser/modal_bottom_sheet
      ref: main
      path: modal_bottom_sheet
  flutter_svg:

  # Utils
  supercharged: ^2.1.1
  intl: ^0.17.0
  share_plus: ^4.5.0
  country_calling_code_picker: ^2.0.1
  font_awesome_flutter: ^10.2.1
  timeago: ^3.3.0
  flutter_contacts: ^1.1.5+1
  app_settings: ^4.1.8
  quiver: ^3.1.0
  transition_plus: 0.0.12
  screenshot: ^1.2.3
  transparent_image: ^2.0.0
  wakelock: ^0.6.2
  flutter_foreground_task: ^3.10.0
  replay_kit_launcher: ^1.0.0

  # Firebase
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.3
  firebase_messaging: ^14.1.0
  cloud_firestore: ^4.1.0
  firebase_database: ^10.0.5

  # Stream
  stream_chat_flutter: ^5.1.0
  stream_chat_persistence: ^5.1.0
  stream_chat_localizations: ^4.0.0

  # Agora
  agora_rtc_engine: ^6.0.0
  flutter_callkit_incoming: ^1.0.2+2

  # Maps
  location: ^4.4.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/prive_app_icon.jpg"

flutter_native_splash:
  background_image: "assets/images/splash_image.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/animations/
    - assets/sounds/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/SF-Pro-Display-BoldItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SF-Pro-Display-MediumItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
        - asset: assets/fonts/SF-Pro-Display-SemiboldItalic.otf