name: prive
description: A Global Communcation App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # App Configs
  cupertino_icons: ^1.0.5
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.5
  easy_localization: ^3.0.1
  flutter_local_notifications: ^9.7.0
  permission_handler: ^10.0.0
  uuid: ^3.0.6

  # State Management
  provider: ^6.0.3
  shared_preferences: ^2.0.15

  # Network
  dio: ^4.0.6
  connectivity_plus: ^2.3.6

  # Audio
  just_audio: ^0.9.28
  record: ^4.3.1

  # Widgets
  cached_network_image: ^3.2.1
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.5+3
  intl_phone_field: ^3.1.0
  pin_code_fields: ^7.4.0
  bot_toast: ^4.0.3
  flutter_staggered_animations: ^1.0.0
  modal_bottom_sheet: ^2.1.0
  flutter_rating_bar: ^4.0.1
  lottie: ^1.3.0
  smooth_page_indicator: ^1.0.0+2
  page_indicator: ^0.4.1
  auto_size_text: ^3.0.0
  convex_bottom_bar: ^3.0.0
  intl_phone_number_input: ^0.7.0+2
  bs_flutter_selectbox: ^1.3.0
  timer_count_down: ^2.2.1
  syncfusion_flutter_sliders: ^20.2.39
  grouped_list: ^5.1.2
  flutter_chat_bubble: ^2.0.0
  cool_dropdown: ^1.4.2
  blur: ^3.1.0
  community_material_icon: ^5.9.55
  country_dial_code: ^1.2.0
  phone_numbers_parser: ^5.0.5
  flutter_sim_country_code: ^0.1.2
  draggable_widget: ^2.0.0
  flip_card: ^0.6.0
  flutter_swipe_action_cell: ^3.0.4
  badges: ^2.0.3
  dashed_circle: ^0.0.2
  story_view: ^0.13.2
  flutter_carousel_slider: ^1.0.9
  google_fonts: ^3.0.1
  map_launcher: ^2.2.3
  carousel_slider: ^4.1.1
  awesome_dialog: ^2.2.1
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg:

  # Utils
  supercharged: ^2.1.1
  intl: ^0.17.0
  share_plus: ^4.0.10
  country_calling_code_picker: ^2.0.1
  font_awesome_flutter: ^10.1.0
  timeago: ^3.2.2
  flutter_contacts: ^1.1.5
  app_settings: ^4.1.8
  quiver: ^3.1.0
  transition_plus: 0.0.12
  screenshot: ^1.2.3
  transparent_image: ^2.0.0
  wakelock: ^0.6.2
  flutter_foreground_task: ^3.8.1

  # Firebase
  firebase_core: ^1.20.0
  firebase_auth: ^3.5.0
  firebase_messaging: ^12.0.1
  cloud_firestore: ^3.4.0
  firebase_database: ^9.0.20

  # Stream
#  stream_chat_flutter:
#    git:
#      path: packages/stream_chat_flutter
#      url: https://github.com/1AhmedYasser/stream-chat-flutter.git
#      ref: develop
  # Stream
  stream_chat_flutter: ^4.4.0
  stream_chat_persistence: ^4.3.0
  stream_chat_localizations: ^3.3.0

  # Agora
  agora_rtc_engine: ^5.3.0
#  flutter_callkit_incoming: ^1.0.2+1
  flutter_callkit_incoming:
    git:
      url: https://github.com/rohithmahesh3/flutter_callkit_incoming
      ref: master
  connectycube_flutter_call_kit: ^2.0.5

  # Maps
  location: ^4.4.0
  geolocator: ^9.0.1
  google_maps_flutter: ^2.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/prive_app_icon.jpg"

flutter_native_splash:
  background_image: "assets/images/splash_image.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/animations/
    - assets/sounds/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/SF-Pro-Display-BoldItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SF-Pro-Display-MediumItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
        - asset: assets/fonts/SF-Pro-Display-SemiboldItalic.otf